<a href="https://colab.research.google.com/github/fbeilstein/machine_learning/blob/master/2_numpy_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Import numpy as np and see the version


**Level 1**

**Problem:**
Import numpy as “np” and print the version number.

In [0]:
# Enter your code here

###Solution:

In [0]:
import numpy as np
print(np.__version__)

1.16.4


##2. How to create a 1D array?



**Level 1**

**Problem:**

Create a 1D array of numbers from 0 to 9

**Expected output:**
```
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [0]:
import numpy as np

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Solution
np.arange(10)

##3. How to create a boolean array?

**Level 1**

**Problem:**

Create a 3x3 numpy array of all True’s

**Expected output:**

```
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])
```

In [0]:
import numpy as np

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Solution
np.full((3, 3), True, dtype=bool)

###Solution B:

In [0]:
import numpy as np

# Solution
np.ones((3,3), dtype=bool)

##4. How to extract items that satisfy a given condition from 1D array?

**Level 1**

**Problem:**
Extract all odd numbers from numpy.array.

**Possible Input:**
```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Desired output:**
```
array([1, 3, 5, 7, 9])
```

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]

##5. How to replace items that satisfy a condition with another value in numpy array?

**Level 1**

**Problem:**
Replace all odd numbers in numpy.array with -1

**Possible Input:**
```
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Expected Output:**
```
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1] = -1
arr

##6. How to replace items that satisfy a condition without affecting the original array?

**Level 2**

**Problem:**
Replace all odd numbers in arr with -1 without changing arr

**Possible Input:**
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Expected Output:**

```
print(' arr = ', arr, '\n out = ', out)
```
```
 arr =  [0 1 2 3 4 5 6 7 8 9] 
 out =  [ 0 -1  2 -1  4 -1  6 -1  8 -1]
```

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Enter your code here

# Output
print(' arr = ', arr, '\n out = ', out)

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
out = np.where(arr % 2 == 1, -1, arr)

# Output
print(' arr = ', arr, '\n out = ', out)

##7. How to reshape an array?

**Level 1**

**Problem:**
Convert a 1D array to a 2D array with 2 rows.

**Possible Input:**
```
arr = np.arange(10)
```

**Expected Output:**
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
```

In [0]:
import numpy as np

# Input
arr = np.arange(10)

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.arange(10)

# Solution
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

##8. How to stack two arrays vertically?



**Level 2**

**Problem:**
Stack arrays a and b vertically

**Possible Input:**
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

**Expected Output:**
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.concatenate([a, b], axis=0)

###Solution B:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.vstack([a, b])

###Solution C:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.r_[a, b]

##9. How to stack two arrays horizontally?

**Level 2**

**Problem:**
Stack the arrays a and b horizontally.

**Possible Input:**
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

**Expected Output:**
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.concatenate([a, b], axis=1)

###Solution B:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.hstack([a, b])

###Solution C:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.c_[a, b]

##10. How to generate custom sequences in numpy without hardcoding?

**Level 2**

**Problem:**
Create the following pattern without hardcoding. Use only numpy functions and the given array a.


**Possible Input:**
```
a = np.array([1,2,3])
```

**Expected Output:**
```
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3])

# Solution
np.r_[np.repeat(a, 3), np.tile(a, 3)]

##11. How to get the common items between two python numpy arrays?

**Level 2**

**Problem:**
Get the common items between a and b

**Possible Input:**
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

**Expected Output:**
```
array([2, 4])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Solution
np.intersect1d(a,b)

##12. How to remove from one array those items that exist in another?

**Level 2**

**Problem:**
From array a remove all items present in array b.

**Possible Input:**
```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

**Expected Output:**
```
array([1, 2, 3, 4])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Solution
np.setdiff1d(a,b)

##13. How to get the positions where elements of two arrays match?

**Level 2**

**Problem:**
Get the positions where elements of a and b match.

**Possible Input:**
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

**Expected Output:**
```
array([1, 3, 5, 7])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Solution
np.where(a == b)[0]

###Solution B:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Solution
np.nonzero(a == b)[0]

##14. How to extract all numbers between a given range from a numpy array?

**Level 2**

**Problem:**
Get all items between 5 and 10 from a.

**Possible Input:**
```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

**Expected Output:**
```
array([ 6,  9, 10])
```

In [0]:
import numpy as np

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Solution
index = np.where((a >= 5) & (a <= 10))
a[index]

###Solution B:

In [0]:
import numpy as np

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Solution
index = np.where(np.logical_and(a >= 5, a <= 10))
a[index]

###Solution C:

In [0]:
import numpy as np

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Solution
a[(a >= 5) & (a <= 10)]

##15. How to make a python function that handles scalars to work on numpy arrays?

**Level 2**

**Problem:**
Convert the function maxx that works on two scalars to work on two arrays.

**Possible Input:**
```
import numpy as np

# Input
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
```

**Expected Output:**
```
array([6., 7., 9., 8., 9., 7., 5.])
```

In [0]:
import numpy as np

# Input
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Solution      
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

##16. How to swap two columns in a 2d numpy array?

**Level 2**

**Problem:**
Swap columns 1 and 2 in the numpy.array.

**Possible Input:**
```
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])
```

**Expected Output:**
```
array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])
```

In [0]:
import numpy as np

# Input
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Enter your code here

###Solution:

In [5]:
import numpy as np

# Input
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Solution
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

##17. How to swap two rows in a 2d numpy array?

**Level 2**

**Problem:**
Swap rows 1 and 2 in the numpy array.

**Possible Input:**
```
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])
```

**Expected Output:**
```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Solution
arr[[1,0,2], :]

##18. How to reverse the rows of a 2D array?

**Level 2**

**Problem:**
Reverse the rows of a 2D array.

**Possible Input:**
```
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])
```

**Expected Output:**
```
array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])
```

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Solution
arr[::-1]


##19. How to reverse the columns of a 2D array?

**Level 2**

**Problem:**
Reverse the columns of a 2D array arr.

**Possible Input:**
```
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])
```

**Expected Output:**
```
array([[5, 4, 3],
       [2, 1, 0],
       [8, 7, 6]])
```

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Solution
arr[:, ::-1]

##20. How to create a 2D array containing random floats between 5 and 10?

**Level 2**

**Problem:**
Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

**No input expected**

**Expected Output:**
Helper function should print "[OK]"

In [0]:
import numpy as np

# helper function to check correctness
def check_array(arr):
  if arr.shape != (5,3):
    print("[ERROR] Wrong shape")
  elif not np.all((rand_arr <= 10.0) & (rand_arr >= 5.0)):
    print("[ERROR] Value outside specified interval")
  else:
    print("[OK]")
########

# Enter your code here

# Check your result
check_array(rand_arr)

###Solution A:

In [0]:
import numpy as np

# Solution
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
rand_arr

###Solution B:

In [0]:
import numpy as np

# Solution
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

##21. How to print only 3 decimal places in python numpy array?

**Level 1**

**Problem:**
Print or show only 3 decimal places of the numpy array rand_arr.

**Possible Input:**
```
rand_arr = np.array([[0.548814, 0.715189, 0.602763],
                     [0.544883, 0.423655, 0.645894],
                     [0.437587, 0.891773, 0.963663],
                     [0.383442, 0.791725, 0.528895],
                     [0.568045, 0.925597, 0.071036]])
```

**Expected Output:**
```
array([[0.549, 0.715, 0.603],
       [0.545, 0.424, 0.646],
       [0.438, 0.892, 0.964],
       [0.383, 0.792, 0.529],
       [0.568, 0.926, 0.071]])
```

In [0]:
import numpy as np

# Input
rand_arr = np.array([[0.548814, 0.715189, 0.602763],
                     [0.544883, 0.423655, 0.645894],
                     [0.437587, 0.891773, 0.963663],
                     [0.383442, 0.791725, 0.528895],
                     [0.568045, 0.925597, 0.071036]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
rand_arr = np.array([[0.548814, 0.715189, 0.602763],
                     [0.544883, 0.423655, 0.645894],
                     [0.437587, 0.891773, 0.963663],
                     [0.383442, 0.791725, 0.528895],
                     [0.568045, 0.925597, 0.071036]])

# Solution
np.set_printoptions(precision=3)
rand_arr

##22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

**Level 1**

**Problem:**
Pretty print rand_arr by suppressing the scientific notation (like 1e10)

**Possible Input:**
```
rand_arr = np.array([[5.434e-04, 2.784e-04, 4.245e-04],
                     [8.448e-04, 4.719e-06, 1.216e-04],
                     [6.707e-04, 8.259e-04, 1.367e-04]])
```

**Expected Output:**
```
array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])
```

In [0]:
import numpy as np

# Input
rand_arr = np.array([[5.434e-04, 2.784e-04, 4.245e-04],
                     [8.448e-04, 4.719e-06, 1.216e-04],
                     [6.707e-04, 8.259e-04, 1.367e-04]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
rand_arr = np.array([[5.434e-04, 2.784e-04, 4.245e-04],
                     [8.448e-04, 4.719e-06, 1.216e-04],
                     [6.707e-04, 8.259e-04, 1.367e-04]])

# Solution
np.set_printoptions(suppress=True, precision=6)
rand_arr

##23. How to limit the number of items printed in output of numpy array?

**Level 1**

**Problem:**
Limit the number of items printed in python numpy array a to a maximum of 6 elements.

**Possible Input:**
```
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

**Expected Output:**
```
array([ 0,  1,  2, ..., 12, 13, 14])
```

In [0]:
import numpy as np

# Input
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution
np.set_printoptions(threshold=6)
a

##24. How to print the full numpy array without truncating

**Level 1**

**Problem:**
Print the full numpy array a without truncating.

**Possible Input:**
```
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

**Expected Output:**
```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

In [0]:
import numpy as np

# Input
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution
np.set_printoptions(threshold=np.inf)
a

##25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

**Level 2**

**Problem:**
Import the iris dataset keeping the text intact.
Print first three rows.

**Possible Input:**
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
```

**Expected Output:**
```
array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)
```

In [0]:
import numpy as np

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# Solution
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:3]

##26. How to extract a particular column from 2D array?

**Level 2**

**Problem:**
Extract the text column "species" from the iris dataset.
Note that species are the fifth column, i.e. has index 4 (indexing starts from 0).
Print first 8 species.

**Possible Input:**
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species_column_num = 4
```

**Expected Output**
```
array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'],
      dtype=object)
```

In [0]:
import numpy as np

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species_column_idx = 4

# Enter your code here

###Solution:

In [1]:
import numpy as np

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species_column_idx = 4

# Solution:
species = iris[:, species_column_idx]
species[:8]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'],
      dtype=object)

##26.5. How to extract a particular column from 1D array of tuples?

**Level 2**

**Problem:**
Extract the text column "species" from the iris dataset.
Note that species are the fifth column, i.e. has index 4 (indexing starts from 0).
Print first 8 species.

**Possible Input:**
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='ascii')
species_column_num = 4
```

**Expected Output**
```
array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
      dtype='<U15')
```

In [0]:
import numpy as np

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
species_column_idx = 4

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='ascii')
species_column_idx = 4

# Solution:
species = np.array([row[species_column_idx] for row in iris_1d])
species[:8]

##27. How to convert a 1d array of tuples to a 2d numpy array?

**Level 2**

**Problem:**
Convert the 1D iris to 2D array iris_2d.
Omit the species text field.
Print forst 4 entries.

**Possible Input:**
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='ascii')
```

**Expected Output:**
```
array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])
```

In [0]:
import numpy as np

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='ascii')

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='ascii')

# Solution:
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

###Solution B:

In [0]:
import numpy as np

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#iris_1d = np.genfromtxt(url, delimiter=',', dtype=None, encoding='ascii')
# ignore this input

# Solution:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3], encoding='ascii')
iris_2d[:4]

##28. How to compute the mean, median, standard deviation of a numpy array?

**Level 1**

**Problem:**
Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

##29. How to normalize an array so the values range exactly between 0 and 1?

**Level 2**

**Problem:**
Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

**Possible Input:**
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(S)

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
S = (sepallength - Smin)/sepallength.ptp() # Thanks, David Ojeda!
print(S)

##30. How to compute the softmax score?

**Level 3**

**Problem:**
Compute the softmax score of sepallength.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
       https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""

    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

print(softmax(sepallength))

##31. How to find the percentile scores of a numpy array?

**Level 1**

**Problem:**
Find the 5th and 95th percentile of iris's sepallength
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
np.percentile(sepallength, q=[5, 95])

##32. How to insert values at random positions in an array?

**Level 2**

**Problem:**
Insert np.nan values at 20 random positions in iris_2d dataset
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 1
i, j = np.where(iris_2d)
# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

# Print first 10 rows
print(iris_2d[:10])

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 2
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Print first 10 rows
print(iris_2d[:10])

##33. How to find the position of missing values in numpy array?

**Level 2**

**Problem:**
Find the number and position of missing values in iris_2d's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

##34. How to filter a numpy array based on two or more conditions?

**Level 3**

**Problem:**

Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and 
sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution
condition = (iris_2d[:, 2] &gt; 1.5) &amp; (iris_2d[:, 0] &lt; 5.0)
iris_2d[condition]

##35. How to drop rows that contain a missing value from a numpy array?
Difficulty Level: L3:@Q. Select the rows of iris_2d that does not have any nan value.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
# No direct numpy function for this.

# Method 1:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:5]

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
# No direct numpy function for this.

# Method 2: (By Rong)
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:5]

##36. How to find the correlation between two columns of a numpy array?

**Level 2**

**Problem:**
Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


# Solution 1
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]

# Correlation coef indicates the degree of linear relationship between two numeric variables.
# It can range between -1 to +1.

# The p-value roughly indicates the probability of an uncorrelated system producing 
# datasets that have a correlation at least as extreme as the one computed.

# The lower the p-value (<0.01), stronger is the significance of the relationship.
# It is not an indicator of the strength.

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


# Solution 2
from scipy.stats.stats import pearsonr 
corr, p_value = pearsonr(iris[:, 0], iris[:, 2])
print(corr)


# Correlation coef indicates the degree of linear relationship between two numeric variables.
# It can range between -1 to +1.

# The p-value roughly indicates the probability of an uncorrelated system producing 
# datasets that have a correlation at least as extreme as the one computed.

# The lower the p-value (<0.01), stronger is the significance of the relationship.
# It is not an indicator of the strength.

##37. How to find if a given array has any null values?

**Level 2**

**Problem:**

Find out if iris_2d has any missing values.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])



np.isnan(iris_2d).any()

##38. How to replace all missing values with 0 in a numpy array?

**Level 2**

**Problem:**

Replace all occurrences of nan with 0 in numpy array
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:4]

##39. How to find the count of unique values in a numpy array?

**Level 2**

**Problem:**
Find the unique values and the count of unique values in iris's species
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Extract the species column as an array
species = np.array([row.tolist()[4] for row in iris])


# Get the unique values and the counts
np.unique(species, return_counts=True)

##40. How to convert a numeric to a categorical (text) array?

**Level 2**

**Problem:**
Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 – 'small', 3-5 – 'medium', >= 5 -- 'large'
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:4]

##41. How to create a new column from existing columns of a numpy array?

**Level 2**

**Problem:**
Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution

# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

# Add the new column
out = np.hstack([iris_2d, volume])

# View
out[:4]

## 42. How to do probabilistic sampling in numpy?

**Level 3**

**Problem:**

Randomly sample iris’s species such that setose is twice the number of versicolor and virginica
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution

# Get the species column
species = iris[:, 4]

# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])

In [0]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution

# Get the species column
species = iris[:, 4]

# Approach 2: Probablistic Sampling (preferred)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

##43. How to get the second largest value of an array when grouped by another array?

**Level 2**

**Problem:**
What is the value of second longest petallength of species setosa
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species and petal length columns
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

# Get the second last value
np.unique(np.sort(petal_len_setosa))[-2]

##44. How to sort a 2D array by a column

**Level 2**

**Problem:**
Sort the iris dataset based on sepallength column.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Sort by column position 0: SepalLength
print(iris[iris[:,0].argsort()][:20])

##45. How to find the most frequent value in a numpy array?

**Level 1**

**Problem:**
Find the most frequent value of petal length (3rd column) in iris dataset.

**Possible Input:**
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution:
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

##46. How to find the position of the first occurrence of a value greater than a given value?

**Level 2**

**Problem:**
Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution: (edit: changed argmax to argwhere. Thanks Rong!)
np.argwhere(iris[:, 3].astype(float) &gt; 1.0)[0]

##47. How to replace all values greater than a given value to a given cutoff?

**Level 2**

**Problem:**
From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

**Possible Input:**
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution 1: Using np.clip
np.clip(a, a_min=10, a_max=30)


# Solution 2: Using np.where
print(np.where(a &lt; 10, 10, np.where(a &gt; 30, 30, a)))

##48. How to get the positions of top n values from a numpy array?

**Level 2**

**Problem:**
Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
print(a.argsort())

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Solution 2:
np.argpartition(-a, 5)[:5]

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Method 1:
a[a.argsort()][-5:]

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Method 2:
np.sort(a)[-5:]

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Method 3:
np.partition(a, kth=-5)[-5:]

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Method 4:
a[np.argpartition(-a, 5)][:5]

##49. How to compute the row wise counts of all possible values in an array?

**Level 4**

**Problem:**
Compute the counts of unique values row-wise.

**Possible Input:**
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

**Expected Output:**
[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

In [0]:
# Solution
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# Print
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

In [0]:
# Example 2:
arr = np.array([np.array(list('bill clinton')), np.array(list('narendramodi')), np.array(list('jjayalalitha'))])
print(np.unique(arr))
counts_of_all_values_rowwise(arr)

##50. How to convert an array of arrays into a flat 1d array?

**Level 4**

**Problem:**
Convert array_of_arrays into a flat linear 1d array.

**Possible Input:**
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays

**Expected Output:**
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# Enter your code here

###Solution:

In [0]:
 # Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

# Solution 1
arr_2d = np.array([a for arr in array_of_arrays for a in arr])

In [0]:
 # Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

# Solution 2:
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

##51. How to generate one-hot encodings for an array in numpy?

**Level 4**

**Problem:**
Compute the one-hot encodings (dummy binary variables for each unique value in the array)


**Possible Input:**
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)


**Expected Output:**
array([[ 0., 1., 0.],
       [ 0., 0., 1.],
       [ 0., 1., 0.],
       [ 0., 1., 0.],
       [ 0., 1., 0.],
       [ 1., 0., 0.]])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

# Solution:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out


one_hot_encodings(arr)

In [0]:
# Input:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

# Solution:
# Method 2:
(arr[:, None] == np.unique(arr)).view(np.int8)

##52. How to create row numbers grouped by a categorical variable?

**Level 3**

**Problem:**
Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

**Possible Input:**
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

**Expected Output:**
[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

In [0]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

##53. How to create groud ids based on a given categorical variable?

**Level 4**

**Problem:**
Create group ids based on a given categorical variable. Use the following sample from iris species as input.

**Possible Input:**


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

In [0]:

**Expected Output:**
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


```python
# Enter your code here

###Solution:

In [0]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

# Solution:
output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]


# Solution: For Loop version
output = []
uniqs = np.unique(species_small)


for val in uniqs: # uniq values in group
    for s in species_small[species_small==val]: # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0] # groupid
        output.append(groupid)

print(output)

##54. How to rank items in an array using numpy?

**Level 2**

**Problem:**

Create the ranks for the given numeric array a.


**Possible Input:**
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)

In [0]:

**Expected Output:**
[4 2 6 0 8 7 9 3 5 1]



```python
# Enter your code here

###Solution:

In [0]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)

# Solution
print(a.argsort().argsort())
print('Array: ', a)

##55. How to rank items in a multidimensional array using numpy?

**Level 3**

**Problem:**
Create a rank array of the same shape as a given numeric array a.


**Possible Input:**
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)


**Expected Output:**
[[4 2 6 0 8]
 [7 9 3 5 1]]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

# Solution
print(a.ravel().argsort().argsort().reshape(a.shape))

##56. How to find the maximum value in each row of a numpy array 2d?

**Level 2**

**Problem:**
Compute the maximum for each row in the given array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

# Solution 1
np.amax(a, axis=1)

In [0]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

# Solution 2
np.apply_along_axis(np.max, arr=a, axis=1)

##57. How to compute the min-by-max for each row for a numpy array 2d?

**Level 3**

**Problem:**
Compute the min-by-max for each row for given 2d numpy array.
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
np.random.seed(100)
a = np.random.randint(1,10, [5,3])

# Solution
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

##58. How to find the duplicate records in a numpy array?

**Level 3**

**Problem:**

Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be False.

**Possible Input:**
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)



**Expected Output:**
[False True False True False False True True True True]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)


## Solution
# There is no direct function to do this as of 1.13.3
# Create an all True array
out = np.full(a.shape[0], True)

# Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]

# Mark those positions as False
out[unique_positions] = False

print(out)

##59. How to find the grouped mean in numpy?

**Level 3**

Find the mean of a numeric column grouped by a categorical column in a 2D numpy array


**Possible Input:**
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


**Expected Output:**
[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.770],
 [b'Iris-virginica', 2.974]]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# No direct way to implement this. Just a version of a workaround.
numeric_column = iris[:, 1].astype('float') # sepalwidth
grouping_column = iris[:, 4] # species

# List comprehension version
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

# For Loop version
output = []
for group_val in np.unique(grouping_column):
output.append([group_val, numeric_column[grouping_column==group_val].mean()])

output

##60. How to convert a PIL image to numpy array?

**Level 3**

**Problem:**
Import the image from the following URL and convert it to a numpy array.
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [0]:
# Enter your code here

###Solution:

In [0]:
from io import BytesIO
from PIL import Image
import PIL, requests

# Import image from URL
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)

# Read it as Image
I = Image.open(BytesIO(response.content))

# Optionally resize
I = I.resize([150,150])

# Convert to numpy array
arr = np.asarray(I)

# Optionaly Convert it back to an image and show
im = PIL.Image.fromarray(np.uint8(arr))
Image.Image.show(im)

##61. How to drop all missing values from a numpy array?

**Level 2**

**Problem:**
Drop all nan values from a 1D numpy array

**Possible Input:**
np.array([1,2,3,np.nan,5,6,7,np.nan])

**Expected Output:**
array([ 1., 2., 3., 5., 6., 7.])

In [0]:
# Enter your code here

###Solution:

In [0]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

##62. How to compute the euclidean distance between two arrays?

**Level 3**

**Problem:**
Compute the euclidean distance between two arrays a and b.


**Possible Input:**
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# Solution
dist = np.linalg.norm(a-b)
dist

##63. How to find all the local maxima (or peaks) in a 1d array?

**Level 4**

**Problem:**
Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

**Possible Input:**


a = np.array([1, 3, 7, 1, 2, 6, 0, 1])


**Expected Output:**
array([2, 5])
where, 2 and 5 are the positions of peak values 7 and 6.

In [0]:
# Enter your code here

###Solution:

In [0]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

##64. How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?

**Level 2**

**Problem:**
Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.

**Possible Input:**
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,1,1]

**Expected Output:**
[[2 2 2]
 [2 2 2]
 [2 2 2]]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])


# Solution
print(a_2d - b_1d[:,None])

##65. How to find the index of n'th repetition of an item in an array

**Level 2**

**Problem:**
Find the index of 5th repetition of number 1 in x.
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [0]:
# Enter your code here

###Solution:

In [0]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

# Solution 1: List comprehension
[i for i, v in enumerate(x) if v == 1][n-1]

In [0]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

# Solution 2: Numpy version
np.where(x == 1)[0][n-1]

66. How to convert numpy's datetime64 object to datetime's datetime object?

**Level 2**

**Problem:**
Convert numpy's datetime64 object to datetime's datetime object
# Input: a numpy datetime64 object
dt64 = np.datetime64('2018-02-25 22:10:10')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input: a numpy datetime64 object
dt64 = np.datetime64('2018-02-25 22:10:10')

# Solution
from datetime import datetime
dt64.tolist()

In [0]:
# Input: a numpy datetime64 object
dt64 = np.datetime64('2018-02-25 22:10:10')

# Solution
dt64.astype(datetime)

##67. How to compute the moving average of a numpy array?

**Level 3**

**Problem:**
Compute the moving average of window size 3, for the given 1D array.

**Possible Input:**
np.random.seed(100)
Z = np.random.randint(10, size=10)

In [0]:
# Enter your code here

###Solution:

In [0]:
# Solution
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)

# Method 1
moving_average(Z, n=3).round(2)

In [0]:
# Solution
np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)

# np.ones(3)/3 gives equal weights. Use np.ones(4)/4 for window size 4.
np.convolve(Z, np.ones(3)/3, mode='valid') . 

##68. How to create a numpy array sequence given only the starting point, length and the step?

**Level 2**

**Problem:**
Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers

In [0]:
# Enter your code here

###Solution:

In [0]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)

seq(start, length, step)

##69. How to fill in missing dates in an irregular series of numpy dates?

**Level 3**

**Problem:**
Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates, by filling in the missing dates.

**Possible Input:**
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

# Solution ---------------
filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)

# add the last day
output = np.hstack([filled_in, dates[-1]])
output


# For loop version -------
out = []
for date, d in zip(dates, np.diff(dates)):
out.append(np.arange(date, (date+d)))

filled_in = np.array(out).reshape(-1)

# add the last day
output = np.hstack([filled_in, dates[-1]])
output

##70. How to create strides from a given 1D array?

**Level 4**

**Problem:**
From the given 1d array arr, generate a 2d matrix using strides, with a window length of 4 and strides of 2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]

**Possible Input:**
arr = np.arange(15) 
arr



**Expected Output:**
[[ 0 1 2 3]
 [ 2 3 4 5]
 [ 4 5 6 7]
 [ 6 7 8 9]
 [ 8 9 10 11]
 [10 11 12 13]]

In [0]:
# Enter your code here

###Solution:

In [0]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])


print(gen_strides(np.arange(15), stride_len=2, window_len=4))