In [2]:
import numpy as np

In [32]:
x = np.array([[
    [[1,2,3,1],[1,4,5,6]],
    [[1,7,8,9],[1,9,8,7]],
    [[1,6,5,4],[1,3,2,1]],
    [[1,6,5,4],[1,3,2,1]]
],[
    [[1,2,3,1],[1,4,5,6]],
    [[1,7,8,9],[1,9,8,7]],
    [[1,6,5,4],[1,3,2,1]],
    [[1,6,5,4],[1,3,2,1]]
]
])

In [33]:
x.shape

(2, 4, 2, 4)

In [37]:
x = np.array([[
    [[1,2,3,1],[1,4,5,6]],
    [[1,7,8,9],[1,9,8,7]],
    [[1,6,5,4],[1,3,2,1]],
    [[1,6,5,4],[1,3,2,1]]
],[
    [[1,2,3,1],[1,4,5,6]],
    [[1,7,8,9],[1,9,8,7]],
    [[1,6,5,4],[1,3,2,1]],
    [[1,6,5,4],[1,3,2,1]]
]
])
print(x.ndim) #рівень вкладеності масиву

x = np.array([
    [[1,2,3,1],[1,4,5,6]],
    [[1,7,8,9],[1,9,8,7]],
    [[1,6,5,4],[1,3,2,1]],
    [[1,6,5,4],[1,3,2,1]]
])
print(x.ndim) #рівень вкладеності масиву


4
3


In [38]:
x = np.array([
    [[1,2,3,1],[1,4,5,6]],
    [[1,7,8,9],[1,9,8,7]],
    [[1,6,5,4],[1,3,2,1]],
    [[1,6,5,4],[1,3,2,1]]
])
x.size

32

In [41]:
np.random.randint(10, size=10)

array([7, 8, 1, 5, 9, 8, 9, 4, 3, 0])

In [58]:
x = np.array([
    [5,0,3,3],
    [7,9,3,5],
    [2,4,7,6]
])

In [59]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [72]:
### Присвоєння масиву через уопію
x = np.array([
    [5,0,3,3],
    [7,9,3,5],
    [2,4,7,6]
])

x2_old = x.copy()
x[0, 0] = 10000 #змінюємо перший елемент оригіналу
x2_old

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [73]:
### Присвоєння масиву через зсилання
x = np.array([
    [5,0,3,3],
    [7,9,3,5],
    [2,4,7,6]
])

x2_old = x
x[0, 0] = 10000 #змінюємо перший елемент оригіналу
x2_old

array([[10000,     0,     3,     3],
       [    7,     9,     3,     5],
       [    2,     4,     7,     6]])

In [103]:
x = np.array([1,2,3,4,5,6,7,8,9,10]) 
a = 1
b = 1
for i in x[:2]:
    a *=i
for i in x[-2:]:
    b *=i

print(b/a)
print(x[::-1]) #перевертає масив
print(x[::-2]) #перевертає масив і виводить через 1
print(x[5::-1]) #перевертає масив і виводить починаючи з 5 елементу


45.0
[10  9  8  7  6  5  4  3  2  1]
[10  8  6  4  2]
[6 5 4 3 2 1]
