<a href="https://colab.research.google.com/github/fbeilstein/machine_learning/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas
pandas.__version__

'0.24.2'

In [0]:
import pandas as pd
pd?

#Introducing Pandas Objects

##The Pandas Series Object

In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [0]:
print(data.values)
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)


In [0]:
print(data[1])
print(data[1:3])

0.5
1    0.50
2    0.75
dtype: float64


In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
print(data)
print(data['b'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.5


In [0]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=[2, 5, 3, 7])
print(data)
print(data[5])

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64
0.5


In [0]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [0]:
population['California']

38332521

In [0]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [0]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [0]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [0]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [0]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

##The Pandas DataFrame Object

In [0]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [0]:
states = pd.DataFrame({'population': population, 'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [0]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [0]:
states.columns

Index(['population', 'area'], dtype='object')

In [0]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [0]:
# From a single Series object.
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [0]:
# From a list of dicts.
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [0]:
# From a list of dicts with MISSING data
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [0]:
# From a dictionary of Series objects.
pd.DataFrame({'population': population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [0]:
# From a two-dimensional NumPy array.
import numpy as np
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

foo       bar
a  0.420290  0.971120
b  0.517206  0.697154
c  0.269252  0.284516

In [0]:
# From a NumPy structured array.
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

##The Pandas Index Object

In [0]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [0]:
ind[1]

3

In [0]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [0]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [0]:
print("index is IMMUTABLE, ERROR should be generated")
ind[1] = 0

index is IMMUTABLE, ERROR should be generated


TypeError: ignored

In [0]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
print(indA & indB) # intersection
print(indA | indB) # union
print(indA ^ indB) # symmetric difference

Int64Index([3, 5, 7], dtype='int64')
Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')
Int64Index([1, 2, 9, 11], dtype='int64')


#Data Indexing and Selection

##Data Selection in Series

In [0]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [0]:
data['b']

0.5

In [0]:
'a' in data

True

In [0]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [0]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [0]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [0]:
# slicing by explicit index
# final index is included in the slice
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [0]:
# slicing by implicit integer index
# final index is excluded from the slice
data[0:2]

a    0.25
b    0.50
dtype: float64

In [0]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [0]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [0]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [0]:
# explicit index when indexing
data[1]

'a'

In [0]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [0]:
# always references the explicit index
print(data.loc[1])
print(data.loc[1:3])

a
1    a
3    b
dtype: object


In [0]:
# always references the implicit index
print(data.iloc[1])
print(data.iloc[1:3])

b
3    b
5    c
dtype: object


##Data Selection in DataFrame

In [0]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [0]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [0]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [0]:
data.area is data['area']

True

In [0]:
data.pop is data['pop'] # conflicts with pop() method of DataFrame

False

In [0]:
data['density'] = data['pop'] / data['area'] # adding new column + elementwise operations
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [0]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [0]:
data.T # transpose

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [0]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [0]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [0]:
data.iloc[:3, :2] # implicit indexing

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [0]:
data.loc[:'Illinois', :'pop'] # explicit indexing

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [0]:
data.loc[data.density > 100, ['pop', 'density']] # fancy indexing + masking

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [0]:
data.iloc[0, 2] = 90 # modification
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [0]:
# while indexing refers to columns, slicing and masking refer to rows
print(data['Florida':'Illinois'])
print(data[1:3])
print(data[data.density > 100])

            area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763
            area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746
            area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121


#Operating on Data in Pandas

##Ufuncs: Index Preservation

In [0]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
print(ser, '\n')

df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
columns=['A', 'B', 'C', 'D'])
print(df)

0    6
1    3
2    7
3    4
dtype: int64 

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4


In [0]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [0]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

##UFuncs: Index Alignment

In [0]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662, 'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127}, name='population')

In [0]:
population / area # missing data is correctly handled (idexes merged)

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [0]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [0]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B # NaN for missing operands

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [0]:
A.add(B, fill_value=0) # treat missing vals as zeros

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [0]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
print(A, '\n\n')
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))
print(B, '\n\n')
A + B

   A   B
0  1  11
1  5   1 


   B  A  C
0  4  0  9
1  5  8  0
2  9  2  6 




A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [0]:
fill = A.stack().mean() # fill missing data with mean value in A
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

##Ufuncs: Operations Between DataFrame and Series

In [0]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [0]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [0]:
df = pd.DataFrame(A, columns=list('QRST')) # broadcasting (row-wise)
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [0]:
df.subtract(df['R'], axis=0) # broadcasting (column-wise)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [0]:
halfrow = df.iloc[0, ::2]
print(halfrow, '\n\n')
print(df - halfrow) # auto-alignment

Q    3
S    2
Name: 0, dtype: int64 


     Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN


#Handling Missing Data

##Missing Data in Pandas

In [1]:
import numpy as np
import pandas as pd

# None is used only in arrays containing Objects
# looks at dtype in the result
vals1 = np.array([1, None, 3, 4])
vals1 

array([1, None, 3, 4], dtype=object)

In [2]:
# using Objects = large overhead
for dtype in ['object', 'int']:
  print("dtype =", dtype)
  %timeit np.arange(1E6, dtype=dtype).sum()
  print()

dtype = object
10 loops, best of 3: 74.3 ms per loop

dtype = int
100 loops, best of 3: 2.19 ms per loop



In [3]:
print("can't sum None, ERROR should be generated")
vals1.sum() 

can't sum None, ERROR should be generated


TypeError: ignored

In [4]:
# use nan as workaround
vals2 = np.array([1, np.nan, 3, 4])
print(vals2.dtype)
print(1 + np.nan)
print(0 * np.nan)
print(vals2.sum(), vals2.min(), vals2.max())

float64
nan
nan
nan nan nan


In [5]:
# skipping nans during operation
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

In [6]:
# converting between nan and None where appropriate
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [8]:
# upcast if needed
x = pd.Series(range(2), dtype=int)
print(x, '\n\n')
x[0] = None
print(x)

0    0
1    1
dtype: int64 


0    NaN
1    1.0
dtype: float64


##Operating on Null Values

In [9]:
data = pd.Series([1, np.nan, 'hello', None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [10]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [11]:
data.dropna()

0        1
2    hello
dtype: object

In [12]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [14]:
# we can only drop full rows or full columns
print(df.dropna(), '\n\n') # rows
print(df.dropna(axis='columns')) # columns

     0    1  2
1  2.0  3.0  5 


   2
0  2
1  5
2  6


In [15]:
df[3] = np.nan
print(df, '\n\n')
df.dropna(axis='columns', how='all') # drop columns that are all nans

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN 




0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [16]:
df.dropna(axis='rows', thresh=3) # keep rows that contain at least 3 elements

0    1  2   3
1  2.0  3.0  5 NaN

In [17]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [18]:
data.fillna(0) # fill nans with zeros

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [19]:
# forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [20]:
# back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [21]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [22]:
df.fillna(method='ffill', axis=1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

In [23]:
df.fillna(method='ffill', axis=0)

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  2.0  4.0  6 NaN

#Hierarchical Indexing

##A Multiply Indexed Series

In [24]:
#bad way
index = [('California', 2000), ('California', 2010),
         ('New York', 2000),   ('New York', 2010),
         ('Texas', 2000),      ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64