<a href="https://colab.research.google.com/github/fbeilstein/machine_learning/blob/master/practice_2_numpy_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Import numpy as np and see the version


**Level 1**

**Problem:**
Import numpy as “np” and print the version number.

In [0]:
# Enter your code here

###Solution:

In [0]:
import numpy as np
print(np.__version__)

##2. How to create a 1D array?



**Level 1**

**Problem:**

Create a 1D array of numbers from 0 to 9

**Expected output:**
```
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [0]:
import numpy as np

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Solution
np.arange(10)

##3. How to create a boolean array?

**Level 1**

**Problem:**

Create a 3x3 numpy array of all True’s

**Expected output:**

```
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])
```

In [0]:
import numpy as np

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Solution
np.full((3, 3), True, dtype=bool)

###Solution B:

In [0]:
import numpy as np

# Solution
np.ones((3,3), dtype=bool)

##4. How to extract items that satisfy a given condition from 1D array?

**Level 1**

**Problem:**
Extract all odd numbers from numpy.array.

**Possible Input:**
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Expected Output:**
```
array([1, 3, 5, 7, 9])
```

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]

##5. How to replace items that satisfy a condition with another value in numpy array?

**Level 1**

**Problem:**
Replace all odd numbers in numpy.array with -1

**Possible Input:**
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Expected Output:**
```
array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
```

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1] = -1
arr

##6. How to replace items that satisfy a condition without affecting the original array?

**Level 2**

**Problem:**
Replace all odd numbers in arr with -1 without changing arr

**Possible Input:**
```python
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

**Expected Output:**
```
 arr =  [0 1 2 3 4 5 6 7 8 9] 
 out =  [ 0 -1  2 -1  4 -1  6 -1  8 -1]
```

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Enter your code here

# Output
print(' arr = ', arr, '\n out = ', out)

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
out = np.where(arr % 2 == 1, -1, arr)

# Output
print(' arr = ', arr, '\n out = ', out)

##7. How to reshape an array?

**Level 1**

**Problem:**
Convert a 1D array to a 2D array with 2 rows.

**Possible Input:**
```python
arr = np.arange(10)
```

**Expected Output:**
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
```

In [0]:
import numpy as np

# Input
arr = np.arange(10)

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.arange(10)

# Solution
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

##8. How to stack two arrays vertically?



**Level 2**

**Problem:**
Stack arrays a and b vertically

**Possible Input:**
```python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

**Expected Output:**
```
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
```

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.concatenate([a, b], axis=0)

###Solution B:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.vstack([a, b])

###Solution C:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.r_[a, b]

##9. How to stack two arrays horizontally?

**Level 2**

**Problem:**
Stack the arrays a and b horizontally.

**Possible Input:**
```python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

**Expected Output:**
```
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
```

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.concatenate([a, b], axis=1)

###Solution B:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.hstack([a, b])

###Solution C:

In [0]:
import numpy as np

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Solution
np.c_[a, b]

##10. How to generate custom sequences in numpy without hardcoding?

**Level 2**

**Problem:**
Create the following pattern without hardcoding. Use only numpy functions and the given array a.


**Possible Input:**
```python
a = np.array([1,2,3])
```

**Expected Output:**
```
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3])

# Solution
np.r_[np.repeat(a, 3), np.tile(a, 3)]

##11. How to get the common items between two python numpy arrays?

**Level 2**

**Problem:**
Get the common items between a and b

**Possible Input:**
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

**Expected Output:**
```
array([2, 4])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Solution
np.intersect1d(a,b)

##12. How to remove from one array those items that exist in another?

**Level 2**

**Problem:**
From array a remove all items present in array b.

**Possible Input:**
```python
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

**Expected Output:**
```
array([1, 2, 3, 4])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Solution
np.setdiff1d(a,b)

##13. How to get the positions where elements of two arrays match?

**Level 2**

**Problem:**
Get the positions where elements of a and b match.

**Possible Input:**
```python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

**Expected Output:**
```
array([1, 3, 5, 7])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Solution
np.where(a == b)[0]

###Solution B:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Solution
np.nonzero(a == b)[0]

##14. How to extract all numbers between a given range from a numpy array?

**Level 2**

**Problem:**
Get all items between 5 and 10 from a.

**Possible Input:**
```python
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

**Expected Output:**
```
array([ 6,  9, 10])
```

In [0]:
import numpy as np

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Solution
index = np.where((a >= 5) & (a <= 10))
a[index]

###Solution B:

In [0]:
import numpy as np

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Solution
index = np.where(np.logical_and(a >= 5, a <= 10))
a[index]

###Solution C:

In [0]:
import numpy as np

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Solution
a[(a >= 5) & (a <= 10)]

##15. How to make a python function that handles scalars to work on numpy arrays?

**Level 2**

**Problem:**
Convert the function maxx that works on two scalars to work on two arrays.

**Possible Input:**
```python
import numpy as np

# Input
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
```

**Expected Output:**
```
array([6., 7., 9., 8., 9., 7., 5.])
```

In [0]:
import numpy as np

# Input
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Solution      
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

##16. How to swap two columns in a 2d numpy array?

**Level 2**

**Problem:**
Swap columns 1 and 2 in the numpy.array.

**Possible Input:**
```python
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])
```

**Expected Output:**
```
array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])
```

In [0]:
import numpy as np

# Input
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Solution
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

##17. How to swap two rows in a 2d numpy array?

**Level 2**

**Problem:**
Swap rows 1 and 2 in the numpy array.

**Possible Input:**
```python
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])
```

**Expected Output:**
```
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Solution
arr[[1,0,2], :]

##18. How to reverse the rows of a 2D array?

**Level 2**

**Problem:**
Reverse the rows of a 2D array.

**Possible Input:**
```python
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])
```

**Expected Output:**
```
array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])
```

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Solution
arr[::-1]


##19. How to reverse the columns of a 2D array?

**Level 2**

**Problem:**
Reverse the columns of a 2D array arr.

**Possible Input:**
```python
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])
```

**Expected Output:**
```
array([[5, 4, 3],
       [2, 1, 0],
       [8, 7, 6]])
```

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Solution
arr[:, ::-1]

##20. How to create a 2D array containing random floats between 5 and 10?

**Level 2**

**Problem:**
Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

**No input expected**

**Expected Output:**
Helper function should print "[OK]"

In [0]:
import numpy as np

# helper function to check correctness
def check_array(arr):
  if arr.shape != (5,3):
    print("[ERROR] Wrong shape")
  elif not np.all((rand_arr <= 10.0) & (rand_arr >= 5.0)):
    print("[ERROR] Value outside specified interval")
  else:
    print("[OK]")
########

# Enter your code here

# Check your result
check_array(rand_arr)

###Solution A:

In [0]:
import numpy as np

# Solution
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
rand_arr

###Solution B:

In [0]:
import numpy as np

# Solution
rand_arr = np.random.uniform(5,10, size=(5,3))
rand_arr

##21. How to print only 3 decimal places in python numpy array?

**Level 1**

**Problem:**
Print or show only 3 decimal places of the numpy array rand_arr.

**Possible Input:**
```python
rand_arr = np.array([[0.548814, 0.715189, 0.602763],
                     [0.544883, 0.423655, 0.645894],
                     [0.437587, 0.891773, 0.963663],
                     [0.383442, 0.791725, 0.528895],
                     [0.568045, 0.925597, 0.071036]])
```

**Expected Output:**
```
array([[0.549, 0.715, 0.603],
       [0.545, 0.424, 0.646],
       [0.438, 0.892, 0.964],
       [0.383, 0.792, 0.529],
       [0.568, 0.926, 0.071]])
```

In [0]:
import numpy as np

# Input
rand_arr = np.array([[0.548814, 0.715189, 0.602763],
                     [0.544883, 0.423655, 0.645894],
                     [0.437587, 0.891773, 0.963663],
                     [0.383442, 0.791725, 0.528895],
                     [0.568045, 0.925597, 0.071036]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
rand_arr = np.array([[0.548814, 0.715189, 0.602763],
                     [0.544883, 0.423655, 0.645894],
                     [0.437587, 0.891773, 0.963663],
                     [0.383442, 0.791725, 0.528895],
                     [0.568045, 0.925597, 0.071036]])

# Solution
np.set_printoptions(precision=3)
rand_arr

##22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

**Level 1**

**Problem:**
Pretty print rand_arr by suppressing the scientific notation (like 1e10)

**Possible Input:**
```python
rand_arr = np.array([[5.434e-04, 2.784e-04, 4.245e-04],
                     [8.448e-04, 4.719e-06, 1.216e-04],
                     [6.707e-04, 8.259e-04, 1.367e-04]])
```

**Expected Output:**
```
array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])
```

In [0]:
import numpy as np

# Input
rand_arr = np.array([[5.434e-04, 2.784e-04, 4.245e-04],
                     [8.448e-04, 4.719e-06, 1.216e-04],
                     [6.707e-04, 8.259e-04, 1.367e-04]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
rand_arr = np.array([[5.434e-04, 2.784e-04, 4.245e-04],
                     [8.448e-04, 4.719e-06, 1.216e-04],
                     [6.707e-04, 8.259e-04, 1.367e-04]])

# Solution
np.set_printoptions(suppress=True, precision=6)
rand_arr

##23. How to limit the number of items printed in output of numpy array?

**Level 1**

**Problem:**
Limit the number of items printed in python numpy array a to a maximum of 6 elements.

**Possible Input:**
```python
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

**Expected Output:**
```
array([ 0,  1,  2, ..., 12, 13, 14])
```

In [0]:
import numpy as np

# Input
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution
np.set_printoptions(threshold=6)
a

##24. How to print the full numpy array without truncating

**Level 1**

**Problem:**
Print the full numpy array a without truncating.

**Possible Input:**
```python
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

**Expected Output:**
```
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
```

In [0]:
import numpy as np

# Input
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Solution
np.set_printoptions(threshold=np.inf)
a

##25. How to import a dataset with numbers and texts keeping the text intact in python numpy?

**Level 2**

**Problem:**
Import the iris dataset keeping the text intact.
Print first three rows.

**Possible Input:**
```python
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
```

**Expected Output:**
```
array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)
```

In [0]:
import numpy as np

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# Solution
iris = np.genfromtxt(url, delimiter=',', dtype='object')
iris[:3]

##26. How to extract a particular column from 2D array?

**Level 2**

**Problem:**
Given 2D array extract one column with specified index.

**Possible Input:**
```python
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5]])
extract_column_idx = 4
```

**Expected Output**
```
array([5, 5, 5, 5])
```

In [0]:
import numpy as np

# Input:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5]])
extract_column_idx = 4

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5]])
extract_column_idx = 4

# Solution:
extracted = arr[:, extract_column_idx]
extracted

##26.5. How to extract a particular column from 1D array of tuples?

**Level 2**

**Problem:**
Given array of tuples extract column specified by given index.

**Possible Input:**
```python
arr = np.array([(1,2,3,4,5),
                (1,2,3,4,5),
                (1,2,3,4,5),
                (1,2,3,4,5)])
extract_column_idx = 4
```

**Expected Output**
```
array([5, 5, 5, 5])
```

In [0]:
import numpy as np

# Input:
arr = np.array([(1,2,3,4,5),
                (1,2,3,4,5),
                (1,2,3,4,5),
                (1,2,3,4,5)])
extract_column_idx = 4

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input:
arr = np.array([(1,2,3,4,5),
                (1,2,3,4,5),
                (1,2,3,4,5),
                (1,2,3,4,5)])
extract_column_idx = 4

# Solution:
extract = np.array([row[extract_column_idx] for row in arr])
extract

##27. How to convert a 1d array of tuples to a 2d numpy array?

**Level 2**

**Problem:**
Convert array of tuples into 2D array.

**Possible Input:**
```python
import numpy as np

# Input:
arr = np.array([( 1, 2, 3, 4),
                ( 5, 6, 7, 8),
                ( 9,10,11,12),
                (13,14,15,16)])
```

**Expected Output:**
```
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
```

In [0]:
import numpy as np

# Input:
arr = np.array([( 1, 2, 3, 4),
                ( 5, 6, 7, 8),
                ( 9,10,11,12),
                (13,14,15,16)])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input:
arr = np.array([( 1, 2, 3, 4),
                ( 5, 6, 7, 8),
                ( 9,10,11,12),
                (13,14,15,16)])

# Solution:
np.array([row.tolist()[:4] for row in arr])

##28. How to compute the mean, median, standard deviation of a numpy array?

**Level 1**

**Problem:**
Find the mean, median, standard deviation of given 1D array.

**Possible input:**
```python
arr = np.array([1,2,3,4,5,6,7,8,9,10])
```

**Expected output:**
```
mean =  5.5 ; median =  5.5 ; deviation =  2.8722813232690143
```

In [0]:
import numpy as np

# Input
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Enter your code here

# Output
print("mean = ", mu, "; median = ", med, "; deviation = ", sd)

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Solution
mu, med, sd = np.mean(arr), np.median(arr), np.std(arr)

# Output
print("mean = ", mu, "; median = ", med, "; deviation = ", sd)

##29. How to normalize an array so the values range exactly between 0 and 1?

**Level 2**

**Problem:**
Create a normalized form of given array -- new values should range exactly between 0 and 1 so that the former minimum corresponds to value 0 and the former maximum corresponds to 1.
Consider appropriate linear trnsformation.

**Possible Input:**
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

**Expected Output:**
```
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])
```

In [0]:
import numpy as np

# Input
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Solution
arr_max, arr_min = arr.max(), arr.min()
arr_norm = (arr - arr_min)/(arr_max - arr_min)
arr_norm

###Solution B:

In [0]:
import numpy as np

# Input
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Solution
arr_max, arr_min = arr.max(), arr.min()
arr_norm = (arr - arr_min)/arr.ptp()
arr_norm

##30. How to compute the softmax score?

**Level 3**

**Problem:**
Compute the softmax score of given array.

**Possible Input:**
```python
arr = np.array([1,2,3,4,5,6,7,8,9,10])
```

**Expected Output:**
```
array([7.80134161e-05, 2.12062451e-04, 5.76445508e-04, 1.56694135e-03,
       4.25938820e-03, 1.15782175e-02, 3.14728583e-02, 8.55520989e-02,
       2.32554716e-01, 6.32149258e-01])
```

In [0]:
import numpy as np

# Input
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Solution
e_arr = np.exp(arr - np.max(arr))
e_arr / e_arr.sum(axis=0) # softmax

##31. How to find the percentile scores of a numpy array?


**Level 1**

**Problem:**
Find the 5th and 95th percentile of given array.

**Possible Input:**
```python
arr = np.array([1,2,3,4,5,6,7,8,9,10])
```

**Expected Output:**
```
array([1.45, 9.55])
```

In [0]:
import numpy as np

# Input
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Solution
np.percentile(arr, q=[5, 95])

##32. How to insert values at random positions in an array?

**Level 2**

**Problem:**
Insert np.nan values at 5 random positions in given array.

**Possible Input:**
```python
np.random.seed(0)
matr = np.array([[1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.]])
```

**Expected Output:**
```
[[ 1.  2.  3. nan  5.]
 [ 1.  2.  3.  4.  5.]
 [ 1.  2.  3.  4.  5.]
 [nan  2. nan  4. nan]
 [ 1. nan  3.  4.  5.]]
```

In [0]:
import numpy as np

# Input
np.random.seed(0)
matr = np.array([[1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.]])

# Enter your code here

# Output
print(matr)

###Solution:

In [0]:
import numpy as np

# Input
np.random.seed(0)
matr = np.array([[1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.],
                 [1.,2.,3.,4.,5.]])

# Solution
matr[np.random.randint(5, size=5), np.random.randint(5, size=5)] = np.nan

# Output
print(matr)

##33. How to find the position of missing values in numpy array?

**Level 2**

**Problem:**
Find the number and position of missing values in given 2D array.

**Possible Input:**
```python
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])
```

**Expected Output:**
```
Number of missing values: 
 2
Position of missing values: 
 (array([2, 3]), array([2, 0]))
```

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])

# Enter your code here

# Output
print("Number of missing values: \n", n_mis)
print("Position of missing values: \n", idx_mis)

###Solution:

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])

# Solution
n_mis = np.isnan(matr[:, :]).sum()
idx_mis = np.where(np.isnan(matr[:, :]))

# Output
print("Number of missing values: \n", n_mis)
print("Position of missing values: \n", idx_mis)

##34. How to filter a numpy array based on two or more conditions?

**Level 3**

**Problem:**
Filter the rows of given array so that value in the 3rd column (index 2) > 1.5 and 
value in the 1st column (index 0) < 5.0

**Possible Input:**
```
matr = np.array([[8, 8, 3, 7, 7],
                 [0, 4, 2, 5, 2],
                 [2, 2, 1, 0, 8],
                 [4, 0, 9, 6, 2],
                 [4, 1, 5, 3, 4]])
```

**Expected Output:**
```
array([[0, 4, 2, 5, 2],
       [4, 0, 9, 6, 2],
       [4, 1, 5, 3, 4]])
```

In [0]:
import numpy as np

# Input
matr = np.array([[8, 8, 3, 7, 7],
                 [0, 4, 2, 5, 2],
                 [2, 2, 1, 0, 8],
                 [4, 0, 9, 6, 2],
                 [4, 1, 5, 3, 4]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
matr = np.array([[8, 8, 3, 7, 7],
                 [0, 4, 2, 5, 2],
                 [2, 2, 1, 0, 8],
                 [4, 0, 9, 6, 2],
                 [4, 1, 5, 3, 4]])

# Solution
condition = (matr[:, 2] > 1) & (matr[:, 0] < 5)
matr[condition]

##35. How to drop rows that contain a missing value from a numpy array?

**Level 3**

**Problem:**
Select the rows of given 2D array that do not have any nan value.

**Possible Input:**
```python
matr = np.array([[1.,    1., 1.,    1., 1.],
                 [2.,    2., 2.,    2., 2.],
                 [3.,    3., np.nan,3., 3.],
                 [np.nan,4., 4.,    4., 4.],
                 [5.,    5., 5.,    5., 5.]])
```

**Expected Output:**
```
array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5.]])
```

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    1., 1.,    1., 1.],
                 [2.,    2., 2.,    2., 2.],
                 [3.,    3., np.nan,3., 3.],
                 [np.nan,4., 4.,    4., 4.],
                 [5.,    5., 5.,    5., 5.]])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    1., 1.,    1., 1.],
                 [2.,    2., 2.,    2., 2.],
                 [3.,    3., np.nan,3., 3.],
                 [np.nan,4., 4.,    4., 4.],
                 [5.,    5., 5.,    5., 5.]])

# Solution
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in matr])
matr[any_nan_in_row][:5]

###Solution B:

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    1., 1.,    1., 1.],
                 [2.,    2., 2.,    2., 2.],
                 [3.,    3., np.nan,3., 3.],
                 [np.nan,4., 4.,    4., 4.],
                 [5.,    5., 5.,    5., 5.]])

# Solution
matr[np.sum(np.isnan(matr), axis = 1) == 0][:5]

##36. How to find the correlation between two columns of a numpy array?

**Level 2**

**Problem:**
Find the correlation between 1st column (index 0) and 3rd column (index 2) of given 2D array.

**Possible Input:**
```python
matr = np.array([[0, 0, 0, 2, 2],
                 [0, 2, 1, 2, 2],
                 [2, 2, 1, 0, 0],
                 [0, 0, 2, 0, 1],
                 [1, 2, 2, 0, 0]])
```

**Expected Output:**
```
0.13363062095621225
```

**Note:**
*   Correlation coef indicates the degree of linear relationship between two numeric variables. It can range between -1 to +1.
*   Besides correlation, p-value is often used. The p-value roughly indicates the probability of an uncorrelated system producing datasets that have a correlation at least as extreme as the one computed. The lower the p-value (<0.01), stronger is the significance of the relationship. But do not use as an indicator of the strength.

In [0]:
import numpy as np

# Input
matr = np.array([[0, 0, 0, 2, 2],
                 [0, 2, 1, 2, 2],
                 [2, 2, 1, 0, 0],
                 [0, 0, 2, 0, 1],
                 [1, 2, 2, 0, 0]])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
matr = np.array([[0, 0, 0, 2, 2],
                 [0, 2, 1, 2, 2],
                 [2, 2, 1, 0, 0],
                 [0, 0, 2, 0, 1],
                 [1, 2, 2, 0, 0]])

# Solution
np.corrcoef(matr[:, 0], matr[:, 2])[0, 1]

###Solution B:

In [0]:
import numpy as np

# Input
matr = np.array([[0, 0, 0, 2, 2],
                 [0, 2, 1, 2, 2],
                 [2, 2, 1, 0, 0],
                 [0, 0, 2, 0, 1],
                 [1, 2, 2, 0, 0]])

# Solution
from scipy.stats.stats import pearsonr 
corr, p_value = pearsonr(matr[:, 0], matr[:, 2])
print(corr)

##37. How to find if a given array has any null values?



**Level 2**

**Problem:**
Find out if given array has any missing values (i.e. np.nan are present).

**Possible Input:**
```python
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])
```

**Expected Output:**
```
True
```

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])

# Solution
np.isnan(matr).any()

##38. How to replace all missing values with 0 in a numpy array?

**Level 2**

**Problem:**
Replace all occurrences of np.nan with 0 in 2D array

**Possible Input:**
```python
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])
```

**Expected Output:**
```
array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 0., 4., 5.],
       [0., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])
```

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
matr = np.array([[1.,    2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.],
                 [1.,    2., np.nan,4., 5.],
                 [np.nan,2., 3.,    4., 5.],
                 [1.,    2., 3.,    4., 5.]])

# Solution
matr[np.isnan(matr)] = 0
matr[:,:]

##39. How to find the count of unique values in a numpy array?

**Level 2**

**Problem:**
Find the unique values and the count of unique values in given array.

**Possible Input:**
```python
arr = np.array([1,2,3,1,2,4])
```

**Expected Output:**
```
(array([1, 2, 3, 4]), array([2, 2, 1, 1]))
```

In [0]:
import numpy as np

# Input 
arr = np.array([1,2,3,1,2,4])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input 
arr = np.array([1,2,3,1,2,4])

# Solution
np.unique(arr, return_counts=True)

##40. How to convert a numeric to a categorical (text) array?

**Level 2**

**Problem:**
Bin the persons' height (given as 1D array) with respect to given bins (1D array) and print their text description (given as 1D array).

Height, m| Description
------------ | -------------
0.0 < h <= 1.7 | short
1.7 < h <= 1.85 | medium
1.85 < h <= 20 | tall
otherwise | alien


**Possible Input:**
```python
height_arr = np.array([1.80, 2.10, 1.90, 1.60, 1.70, 1.65, 1.75])
bins = [0.0, 1.7, 1.85, 2.0]
label_map = ['short', 'medium', 'tall', 'alien']
```

**Expected Output:**
```
['medium', 'alien', 'tall', 'short', 'medium', 'short', 'medium']
```

In [0]:
import numpy as np

# Input
height_arr = np.array([1.80, 2.10, 1.90, 1.60, 1.70, 1.65, 1.75])
bins = [0.0, 1.7, 1.85, 2.0]
label_map = ['short', 'medium', 'tall', 'alien']

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
height_arr = np.array([1.80, 2.10, 1.90, 1.60, 1.70, 1.65, 1.75])
bins = [0.0, 1.7, 1.85, 2.0]
label_map = ['short', 'medium', 'tall', 'alien']

# Solution
height_bin = np.digitize(height_arr, bins)
[label_map[x-1] for x in height_bin]

##41. How to create a new column from existing columns of a numpy array?

**Level 2**

**Problem:**
Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution

# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

# Add the new column
out = np.hstack([iris_2d, volume])

# View
out[:4]

## 42. How to do probabilistic sampling in numpy?

**Level 3**

**Problem:**

Randomly sample iris’s species such that setose is twice the number of versicolor and virginica
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution

# Get the species column
species = iris[:, 4]

# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])

In [0]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution

# Get the species column
species = iris[:, 4]

# Approach 2: Probablistic Sampling (preferred)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
print(np.unique(species_out, return_counts=True))

##43. How to get the second largest value of an array when grouped by another array?

**Level 2**

**Problem:**
What is the value of second longest petallength of species setosa
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution
# Get the species and petal length columns
petal_len_setosa = iris[iris[:, 4] == b'Iris-setosa', [2]].astype('float')

# Get the second last value
np.unique(np.sort(petal_len_setosa))[-2]

1.7

##44. How to sort a 2D array by a column

**Level 2**

**Problem:**
Sort the iris dataset based on sepallength column.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Sort by column position 0: SepalLength
print(iris[iris[:,0].argsort()][:20])

##45. How to find the most frequent value in a numpy array?

**Level 1**

**Problem:**
Find the most frequent value of petal length (3rd column) in iris dataset.

**Possible Input:**
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution:
vals, counts = np.unique(iris[:, 2], return_counts=True)
print(vals[np.argmax(counts)])

##46. How to find the position of the first occurrence of a value greater than a given value?

**Level 2**

**Problem:**
Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Solution: (edit: changed argmax to argwhere. Thanks Rong!)
np.argwhere(iris[:, 3].astype(float) &gt; 1.0)[0]

##47. How to replace all values greater than a given value to a given cutoff?

**Level 2**

**Problem:**
From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

**Possible Input:**
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution 1: Using np.clip
np.clip(a, a_min=10, a_max=30)


# Solution 2: Using np.where
print(np.where(a &lt; 10, 10, np.where(a &gt; 30, 30, a)))

##48. How to get the positions of top n values from a numpy array?

**Level 2**

**Problem:**
Get the positions of top 5 maximum values in a given array a.
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
print(a.argsort())

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Solution 2:
np.argpartition(-a, 5)[:5]

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Method 1:
a[a.argsort()][-5:]

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Method 2:
np.sort(a)[-5:]

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Method 3:
np.partition(a, kth=-5)[-5:]

In [0]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 20)

# Solution:
# Method 4:
a[np.argpartition(-a, 5)][:5]

##49. How to compute the row wise counts of all possible values in an array?

**Level 4**

**Problem:**
Compute the counts of unique values row-wise.

**Possible Input:**
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

**Expected Output:**
[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

In [0]:
# Solution
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# Print
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

In [0]:
# Example 2:
arr = np.array([np.array(list('bill clinton')), np.array(list('narendramodi')), np.array(list('jjayalalitha'))])
print(np.unique(arr))
counts_of_all_values_rowwise(arr)

##50. How to convert an array of arrays into a flat 1d array?

**Level 4**

**Problem:**
Convert array of arrays into a flat linear 1d array.

**Possible Input:**
```python
import numpy as np

# Input:
array_2d = np.array([np.array([0, 1, 2]), 
                     np.array([3, 4, 5, 6]), 
                     np.array([7, 8, 9])])
```

**Expected Output:**
```
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [0]:
import numpy as np

# Input:
array_2d = np.array([np.array([0, 1, 2]), 
                     np.array([3, 4, 5, 6]), 
                     np.array([7, 8, 9])])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input:
array_2d = np.array([np.array([0, 1, 2]), 
                     np.array([3, 4, 5, 6]), 
                     np.array([7, 8, 9])])

# Solution:
np.array([a for arr in array_2d for a in arr])

###Solution B:

In [0]:
import numpy as np

# Input:
array_2d = np.array([np.array([0, 1, 2]), 
                     np.array([3, 4, 5, 6]), 
                     np.array([7, 8, 9])])

# Solution:
np.concatenate(array_2d)

##51. How to generate one-hot encodings for an array in numpy?

**Level 4**

**Problem:**
Compute the one-hot encodings (dummy binary variables for each unique value in the array)


**Possible Input:**
```python
arr = np.array([4, 2, 6, 4, 2, 6])
```

**Expected Output:**
```
array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]], dtype=int8)
```

**Explanation:**
Every unique value should have its corresponding "bit".
Set it to 1 when the value occurs, 0 otherwise.
As a result you should get array of arrays, every subarray should contain one 1 and many 0-s.

**Note:**
This encoding is used in ML to deal with categorical variables.

In [0]:
import numpy as np

# Input:
arr = np.array([4, 2, 6, 4, 2, 6])

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input:
arr = np.array([4, 2, 6, 4, 2, 6])

# Solution:
uniques = np.unique(arr)
out = np.zeros((arr.shape[0], uniqs.shape[0]), dtype=np.int8)
for i, k in enumerate(arr):
  out[i, np.where(uniques == k)] = 1
out

###Solution B:

In [0]:
import numpy as np

# Input:
arr = np.array([4, 2, 6, 4, 2, 6])

# Solution:
(arr[:, None] == np.unique(arr)).view(np.int8)

##52. How to create row numbers grouped by a categorical variable?

**Level 3**

**Problem:**
Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

**Possible Input:**
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

**Expected Output:**
[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

In [0]:
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

##53. How to create groud ids based on a given categorical variable?

**Level 4**

**Problem:**
Create group ids based on a given categorical variable. Use the following sample from iris species as input.

**Possible Input:**


url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

In [0]:

**Expected Output:**
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


```python
# Enter your code here

###Solution:

In [0]:
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

# Solution:
output = [np.argwhere(np.unique(species_small) == s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]


# Solution: For Loop version
output = []
uniqs = np.unique(species_small)


for val in uniqs: # uniq values in group
    for s in species_small[species_small==val]: # each element in group
        groupid = np.argwhere(uniqs == s).tolist()[0][0] # groupid
        output.append(groupid)

print(output)

##54. How to rank items in an array using numpy?

**Level 2**

**Problem:**
Create ranks for the given numeric array.

**Possible Input:**
```python
a = np.array([9, 4, 15, 0, 17, 16, 17, 8, 9, 0])
```

**Expected Output:**
```
array([4, 2, 6, 0, 8, 7, 9, 3, 5, 1])
```

**Explanation:**
*   Sort initial array [ 0,  0,  4,  8,  9,  9, 15, 16, 17, 17]
*   4 has index 2 in the new array
*   place 2 instead of 4 into the initial array

In [0]:
import numpy as np

# Input
a = np.array([9, 4, 15, 0, 17, 16, 17, 8, 9, 0])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([9, 4, 15, 0, 17, 16, 17, 8, 9, 0])

# Solution
a.argsort().argsort()

##55. How to rank items in a multidimensional array using numpy?

**Level 3**

**Problem:**
Create a rank array of the same shape as a given numeric array, i.e. new array should contain numbers that correspond to the position of each item of the initial array if it had been flattened and sorted.


**Possible Input:**
```python
a = np.array([[ 65,  31,  57,  36,  27],
              [ 18,  93,  77, 150, 151]])
```

**Expected Output:**
```
array([[5, 2, 4, 3, 1],
       [0, 7, 6, 8, 9]])
```

**Explanation:**
*   Flatten initial array [ 65,  31,  57,  36,  27,  18,  93,  77, 150, 151]
*   Sort it [ 18,  27,  31,  36,  57,  65,  77,  93, 150, 151]
*   Consider 18, it has index 0 in the sorted array
*   Place 0 instead of 18 into initial array
*   Consider all the rest numbers same way

In [0]:
import numpy as np

# Input:
a = np.array([[ 65,  31,  57,  36,  27],
              [ 18,  93,  77, 150, 151]])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input:
a = np.array([[ 65,  31,  57,  36,  27],
              [ 18,  93,  77, 150, 151]])

# Solution
a.ravel().argsort().argsort().reshape(a.shape)

##56. How to find the maximum value in each row of a numpy array 2d?

**Level 2**

**Problem:**
Compute the maximum for each row of the given array.

**Possible Input:**
```python
a = [[9, 9, 4],
 [8, 8, 1],
 [5, 3, 6],
 [3, 3, 3],
 [2, 1, 9]]
```

**Expected Output:**
```
array([9, 8, 6, 3, 9])
```

In [0]:
import numpy as np

# Input
a = [[9, 9, 4],
 [8, 8, 1],
 [5, 3, 6],
 [3, 3, 3],
 [2, 1, 9]]

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
a = [[9, 9, 4],
 [8, 8, 1],
 [5, 3, 6],
 [3, 3, 3],
 [2, 1, 9]]

# Solution:
np.amax(a, axis=1)

###Solution B:

In [0]:
import numpy as np

# Input
a = [[9, 9, 4],
 [8, 8, 1],
 [5, 3, 6],
 [3, 3, 3],
 [2, 1, 9]]

# Solution:
np.apply_along_axis(np.max, arr=a, axis=1)

##57. How to compute the min-by-max for each row for a numpy array 2d?

**Level 3**

**Problem:**
Compute the min divided by max for each row of the given 2d numpy array.

**Possible Input:**
```python
a = [[9, 9, 4],
     [8, 8, 1],
     [5, 3, 6],
     [3, 3, 3],
     [2, 1, 9]]
```

**Expected Output:**
```
array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])
```

In [0]:
import numpy as np

# Input
a = [[9, 9, 4],
     [8, 8, 1],
     [5, 3, 6],
     [3, 3, 3],
     [2, 1, 9]]

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = [[9, 9, 4],
     [8, 8, 1],
     [5, 3, 6],
     [3, 3, 3],
     [2, 1, 9]]

# Solution
np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr=a, axis=1)

##58. How to find the duplicate records in a numpy array?

**Level 3**

**Problem:**
Find the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as True. First time occurrences should be marked as False.

**Possible Input:**
```python
arr = np.array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])
```

**Expected Output:**
```
array([False,  True, False,  True, False, False,  True,  True,  True,
        True])
```

In [0]:
import numpy as np

# Input
arr = np.array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
arr = np.array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

# Solution:
out = np.full(a.shape[0], True)
unique_positions = np.unique(a, return_index=True)[1]
out[unique_positions] = False
out

##59. How to find the grouped mean in numpy?

**Level 3**

Find the mean of a numeric column grouped by a categorical column in a 2D numpy array


**Possible Input:**
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


**Expected Output:**
[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.770],
 [b'Iris-virginica', 2.974]]

In [0]:
# Enter your code here

###Solution:

In [0]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# No direct way to implement this. Just a version of a workaround.
numeric_column = iris[:, 1].astype('float') # sepalwidth
grouping_column = iris[:, 4] # species

# List comprehension version
[[group_val, numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]

# For Loop version
output = []
for group_val in np.unique(grouping_column):
output.append([group_val, numeric_column[grouping_column==group_val].mean()])

output

##60. How to convert a PIL image to numpy array?

**Level 3**

**Problem:**
Given image as numpy array (every pixel is RGB triple, each component varies from 0 to 255) invert colors.

**Possible Input:**
```python
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)
I = Image.open(BytesIO(response.content))
I = I.resize([150,150])
arr = np.asarray(I)
```

**Expected Output:**
Two images, one has inverted colors.

In [0]:
from io import BytesIO
from PIL import Image
import PIL, requests
from IPython.display import display

# Input
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)
I = Image.open(BytesIO(response.content))
I = I.resize([150,150])
arr = np.asarray(I)

# Enter your code here

# Output
im = PIL.Image.fromarray(np.uint8(arr))
display(im, I)

###Solution:

In [0]:
from io import BytesIO
from PIL import Image
import PIL, requests
from IPython.display import display

# Input
URL = 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'
response = requests.get(URL)
I = Image.open(BytesIO(response.content))
I = I.resize([150,150])
arr = np.asarray(I)

#Solution
arr = 255 - arr

# Output
im = PIL.Image.fromarray(np.uint8(arr))
display(im, I)

##61. How to drop all missing values from a numpy array?

**Level 2**

**Problem:**
Drop all nan values from a 1D numpy array

**Possible Input:**
```python
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
```

**Expected Output:**
```
array([1., 2., 3., 5., 6., 7.])
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

# Solution
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

##62. How to compute the euclidean distance between two arrays?

**Level 3**

**Problem:**
Compute the euclidean distance between two arrays.


**Possible Input:**
```python
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
```

**Expected Output:**
```
6.708203932499369
```

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# Solution
np.linalg.norm(a-b)

6.708203932499369

##63. How to find all the local maxima (or peaks) in a 1d array?

**Level 4**

**Problem:**
Find all the peaks in a 1D numpy array.
Peaks are points surrounded by smaller values on both sides.

**Possible Input:**
```python
import numpy as np

# Input
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```

**Expected Output:**
```
array([2, 5])
```

In [0]:
import numpy as np

# Input
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# Solution
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

##64. How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?


**Level 2**

**Problem:**
Subtract the 1d array from the 2d array. 
Each item of b_1d should be subtracted from respective row of a_2d.

**Possible Input:**
```python
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
```

**Expected Output:**
```
array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])
```

In [0]:
import numpy as np

# Input
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])


# Solution
a_2d - b_1d[:,None]

##65. How to find the index of n'th repetition of an item in an array

**Level 2**

**Problem:**
Find the index of 5th repetition of number 1 in x.

**Possible input:**
```
import numpy as np

# Input:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
```

**Expected output:**
```
8
```

In [0]:
import numpy as np

# Input:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

# Solution:
[i for i, v in enumerate(x) if v == 1][n-1]

###Solution B:

In [0]:
import numpy as np

# Input:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

# Solution:
np.where(x == 1)[0][n-1]

##66. How to convert numpy's datetime64 object to datetime's datetime object?

**Level 2**

**Problem:**
Convert given numpy's datetime64 object to datetime's datetime object

**Possible input:**
```python
dt64 = np.datetime64('2018-02-25 22:10:10')
```

**Expected Output:**
```
datetime.datetime(2018, 2, 25, 22, 10, 10)
```

In [0]:
import numpy as np
from datetime import datetime

# Input:
dt64 = np.datetime64('2018-02-25 22:10:10')

# Enter your code here

###Solution A:

In [0]:
import numpy as np
from datetime import datetime

# Input:
dt64 = np.datetime64('2018-02-25 22:10:10')

# Solution
dt64.tolist()

###Solution B:

In [0]:
import numpy as np
from datetime import datetime

# Input:
dt64 = np.datetime64('2018-02-25 22:10:10')

# Solution
dt64.astype(datetime)

##67. How to compute the moving average of a numpy array?

**Level 3**

**Problem:**
Compute the moving average.
Window size and 1D array are given.

**Possible Input:**
```python
import numpy as np

# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
wnd = 3
```

**Expected Output:**
```
array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])
```

In [0]:
import numpy as np

# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
wnd = 3

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
wnd = 3

# Solution
avg = np.cumsum(arr, dtype=float)
avg[wnd:] = avg[wnd:] - avg[:-wnd]
avg = avg[wnd-1:]/wnd
avg.round(2)

###Solution B:

In [0]:
import numpy as np

# Input
arr = np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2])
wnd = 3

# Solution
np.convolve(arr, np.ones(wnd)/wnd, mode='valid').round(2)

##68. How to create a numpy array sequence given only the starting point, length and the step?




**Level 2**

**Problem:**
Create a numpy array of given length that starts with given number and has a given step between consecutive numbers.
Print the result for length = 10, start = 5, and step = 3.

**Possible input:**
```
length = 10
start  = 5
step   = 3

```

**Expected output:**
```
array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])
```

In [0]:
# Input
length = 10
start  = 5
step   = 3

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
length = 10
start  = 5
step   = 3

# Solution:
np.arange(start, start + step * length, step)

##68.5. How to create a numpy array sequence of dates?




**Level 3**

**Problem:**
Create a numpy array that contains dates of every other day between 2019-02-01 and 2019-02-25.

**Possible input:**
```
start = '2019-02-01'
end   = '2019-02-25'
step  = 2
```

**Expected output:**
```
array(['2019-02-01', '2019-02-03', '2019-02-05', '2019-02-07',
       '2019-02-09', '2019-02-11', '2019-02-13', '2019-02-15',
       '2019-02-17', '2019-02-19', '2019-02-21', '2019-02-23'],
      dtype='datetime64[D]')
```

In [0]:
import numpy as np

# Input
start = '2019-02-01'
end   = '2019-02-25'
step  = 2

# Enter your code here

###Solution:

In [0]:
import numpy as np

# Input
start = '2019-02-01'
end   = '2019-02-25'
step  = 2

# Solution:
dates = np.arange(np.datetime64(start), np.datetime64(end), step)
dates

##69. How to fill in missing dates in an irregular series of numpy dates?


**Level 3**

**Problem:**
Given an array of a non-continuous sequence of dates. Make it a continuous sequence of dates by filling in the missing dates.

**Possible Input:**
```python
dates = np.array(['2019-02-01', '2019-02-03', '2019-02-05', '2019-02-07',
                  '2019-02-09', '2019-02-11', '2019-02-13', '2019-02-15',
                  '2019-02-17', '2019-02-19', '2019-02-21', '2019-02-23'],
                 dtype='datetime64[D]')
```

**Expeced output:**
```
array(['2019-02-01', '2019-02-02', '2019-02-03', '2019-02-04',
       '2019-02-05', '2019-02-06', '2019-02-07', '2019-02-08',
       '2019-02-09', '2019-02-10', '2019-02-11', '2019-02-12',
       '2019-02-13', '2019-02-14', '2019-02-15', '2019-02-16',
       '2019-02-17', '2019-02-18', '2019-02-19', '2019-02-20',
       '2019-02-21', '2019-02-22', '2019-02-23'], dtype='datetime64[D]')
```

In [0]:
import numpy as np

# Input
dates = np.array(['2019-02-01', '2019-02-03', '2019-02-05', '2019-02-07',
                  '2019-02-09', '2019-02-11', '2019-02-13', '2019-02-15',
                  '2019-02-17', '2019-02-19', '2019-02-21', '2019-02-23'],
                 dtype='datetime64[D]')

# Enter your code here

###Solution A:

In [0]:
import numpy as np

# Input
dates = np.array(['2019-02-01', '2019-02-03', '2019-02-05', '2019-02-07',
                  '2019-02-09', '2019-02-11', '2019-02-13', '2019-02-15',
                  '2019-02-17', '2019-02-19', '2019-02-21', '2019-02-23'],
                 dtype='datetime64[D]')

# Solution:
filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)
output = np.hstack([filled_in, dates[-1]])
output


###Solution B:

In [0]:
import numpy as np

# Input
dates = np.array(['2019-02-01', '2019-02-03', '2019-02-05', '2019-02-07',
                  '2019-02-09', '2019-02-11', '2019-02-13', '2019-02-15',
                  '2019-02-17', '2019-02-19', '2019-02-21', '2019-02-23'],
                 dtype='datetime64[D]')

# Solution:
out = []
for date, d in zip(dates, np.diff(dates)):
  out.append(np.arange(date, (date+d)))

filled_in = np.array(out).reshape(-1)
output = np.hstack([filled_in, dates[-1]])
output

##70. How to create strides from a given 1D array?


**Level 4**

**Problem:**
Implement function that generates 1D array by given 2D matrix.
Rows of matrix should represent window of given size (wnd) copied for 1D array with stride (strd).
Print result for 1D array [1,2,3,...,14], wnd=4, and strd=2.

**Possible Input:**
```python
arr = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
window_sz = 4
stride = 2
```

**Expected Output:**
```
array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])
```

In [0]:
import numpy as np

def gen_strides(a, strd, wnd):
  # Enter your code here


# Input:
arr = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
window_sz = 4
stride = 2

# Output:
gen_strides(arr, stride, window_sz)


###Solution:

In [0]:
import numpy as np

def gen_strides(a, strd, wnd):
  # Solution:
  n_strides = 1 + (a.size - wnd) // strd
  return np.array([a[s:(s+wnd)] for s in np.arange(0, n_strides*strd, strd)])

# Input:
arr = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
window_sz = 4
stride = 2

# Output:
gen_strides(arr, stride, window_sz)